#!/usr/bin/env python3
"""Regenerate docs/CURRICULUM-MAP.md — the canonical lessons ⇄ subjects ⇄ exercises index.

Self-contained (no running server needed). Merges four repo sources:
  1. lessons/*.md            → learning order (NN[x]- prefix) + each lesson's title
  2. gui/index.html          → CONCEPT_LESSON (exercise concept → lesson id)
  3. exercises/*/*.toml       → each exercise's id, concept, expected_error_code (path order)
  4. docs/curriculum-subjects.json → per-lesson subject + "teaches" (editable authoring data)

Run from the repo root:  python3 scripts/build-curriculum-map.py
Edit docs/curriculum-subjects.json to refine a lesson's subject, then re-run.
"""
import json
import re
import glob
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)


def lesson_sort_key(fname):
    """(major, suffix) so 5 sorts before 5b before 5c — the order the app serves."""
    m = re.match(r"(\d+)([a-z]*)-", fname)
    return (int(m.group(1)), m.group(2)) if m else (999, fname)


def load_lessons():
    files = sorted((os.path.basename(p) for p in glob.glob("lessons/*.md")), key=lesson_sort_key)
    order, titles = [], {}
    for f in files:
        lid = f[:-3]
        order.append(lid)
        first_h1 = ""
        with open(os.path.join("lessons", f), encoding="utf-8") as fh:
            for line in fh:
                if line.startswith("# "):
                    first_h1 = line[2:].strip()
                    break
        titles[lid] = first_h1 or lid
    return order, titles


def load_concept_lesson():
    html = open("gui/index.html", encoding="utf-8").read()
    m = re.search(r"const CONCEPT_LESSON = \{(.*?)\};", html, re.S)
    return dict(re.findall(r"'([^']+)':\s*'([^']+)'", m.group(1)))


def load_exercises(cl, idx_of, titles):
    rows = []
    for t in sorted(glob.glob("exercises/*/*.toml")):
        txt = open(t, encoding="utf-8").read()

        def field(k):
            mm = re.search(rf'^{k}\s*=\s*"([^"]*)"', txt, re.M)
            return mm.group(1) if mm else ""

        exid, concept, code = field("id"), field("concept"), field("expected_error_code")
        lid = cl.get(concept, "")
        rows.append({"id": exid, "concept": concept, "code": code,
                     "lesson": lid, "lesson_idx": idx_of.get(lid, -1)})
    return rows


def esc(s):
    return (s or "").replace("|", "\\|")


def main():
    order, titles = load_lessons()
    idx_of = {lid: i for i, lid in enumerate(order)}
    cl = load_concept_lesson()
    exs = load_exercises(cl, idx_of, titles)
    subj = json.load(open("docs/curriculum-subjects.json", encoding="utf-8"))

    reverse = {lid: [] for lid in order}
    for e in exs:
        if e["lesson"] in reverse:
            reverse[e["lesson"]].append(e["id"])
    no_ex = [lid for lid in order if not reverse[lid]]
    pileups = sorted(((lid, len(v)) for lid, v in reverse.items() if len(v) >= 3),
                     key=lambda x: -x[1])

    o = []
    w = o.append
    w("# Curriculum Map — lessons ⇄ subjects ⇄ exercises\n")
    w("> **Purpose.** One canonical index for the whole Rust course: every lesson's subject, "
      "what it teaches, and which exercise (if any) practices it — plus the reverse. Use it to "
      "sequence exercises against lessons, spot gaps, and author or adjust lessons without "
      "re-reading the whole corpus each time.\n")
    w("> **Source of truth.** Lesson order = the `NN[x]-` file prefixes under `lessons/`. "
      "Exercise→lesson mapping = `CONCEPT_LESSON` in `gui/index.html` (keyed by each exercise's "
      "`concept`). Subjects live in `docs/curriculum-subjects.json` (editable). "
      "**Generated by `scripts/build-curriculum-map.py` — do not hand-edit; re-run it.**\n")
    w(f"> **Totals.** {len(order)} lessons · {len(exs)} exercises · {len(no_ex)} lessons with no exercise yet.\n")
    w("\n---\n")

    w("\n## 1 · Lessons in learning order — subject → exercises\n")
    w("Each lesson, in the order the app presents it, with its subject and the exercise(s) that practice it.\n")
    w("\n| # | Lesson | Subject | Practiced by |")
    w("|---|--------|---------|--------------|")
    for i, lid in enumerate(order):
        s = subj.get(lid, {}).get("subject", "")
        prac = reverse.get(lid, [])
        prac_s = ", ".join(f"`{p}`" for p in prac) if prac else "_— none yet_"
        w(f"| {i} | **{esc(titles.get(lid, lid))}**<br>`{lid}` | {esc(s)} | {prac_s} |")

    w("\n---\n")
    w("\n## 2 · Exercises in current order → lesson (alignment check)\n")
    w("Exercises in the order the app serves them (`NN-phase/NN_name` file order). The **L#** is the "
      "learning-order index of the lesson each one points at. **⬅ back** flags where the lesson index "
      "drops below the previous exercise's — the learner is bounced to an *earlier* lesson than the one "
      "before. A perfectly aligned course would have **no** back-jumps.\n")
    w("\n| # | Exercise | Concept | Err | → Lesson | L# | |")
    w("|---|----------|---------|-----|----------|----|--|")
    prev, backs = -1, 0
    for i, e in enumerate(exs):
        li = e["lesson_idx"]
        flag = ""
        if 0 <= li < prev:
            flag = "⬅ **back**"
            backs += 1
        if li >= 0:
            prev = li
        w(f"| {i + 1} | `{e['id']}` | {esc(e['concept'])} | {e['code'] or '—'} | `{e['lesson']}` | {li} | {flag} |")
    w(f"\n**{backs} backward jumps** in the current order — the concrete reason the course doesn't "
      "walk Lesson 1 → 2 → 3 in step.\n")

    w("\n---\n")
    w("\n## 3 · Alignment analysis & re-sequencing blueprint\n")
    w("**The headline problems**\n")
    w("- The **first** exercise points at **Lesson 2** while **Lesson 1** is practiced by the *last* "
      "basics exercise — so the course opens on Lesson 2 (the \"why isn't it starting on Lesson 1\" report).\n")
    w("- Big forward leaps mid-section bounce the learner far ahead, then back.\n")
    w("- **Pile-ups**: several lessons carry many exercises while others carry none:\n")
    for lid, n in pileups:
        w(f"  - **{n}×** `{lid}` — {esc(titles.get(lid, lid))}\n")
    w("\n**Proposed aligned order** (exercises sorted by the lesson they teach, then current order). "
      "A *starting point* for the re-sequence, not auto-applied — difficulty/dependencies may justify "
      "local tweaks:\n")
    w("\n| new # | Exercise | → Lesson | L# |")
    w("|-------|----------|----------|----|")
    aligned = sorted(enumerate(exs),
                     key=lambda p: (p[1]["lesson_idx"] if p[1]["lesson_idx"] >= 0 else 999, p[0]))
    for n, (i, e) in enumerate(aligned):
        w(f"| {n + 1} | `{e['id']}` | `{e['lesson']}` | {e['lesson_idx']} |")

    w("\n---\n")
    w("\n## 4 · Lessons with no exercise yet (gap list)\n")
    w(f"{len(no_ex)} of {len(order)} lessons have no paired exercise — candidates for new authoring. "
      "In learning order:\n")
    for lid in order:
        if lid in no_ex:
            s = subj.get(lid, {}).get("subject", "")
            w(f"- `{lid}` — **{esc(titles.get(lid, lid))}** — {esc(s)}")

    w("\n---\n")
    w("\n## 5 · Per-lesson detail (subject + what it teaches)\n")
    w("The authoring reference: every lesson's subject and the concrete things it covers.\n")
    for i, lid in enumerate(order):
        d = subj.get(lid, {})
        w(f"\n**L{i} · {titles.get(lid, lid)}** — `lessons/{lid}.md`  ")
        w(f"{d.get('subject', '')}  ")
        if d.get("teaches"):
            w("Teaches: " + "; ".join(d["teaches"]))

    w("\n---\n")
    w("\n## 6 · How to regenerate\n")
    w("Run `python3 scripts/build-curriculum-map.py` from the repo root. It re-reads the lesson "
      "files, the `CONCEPT_LESSON` map, the exercise tomls, and `docs/curriculum-subjects.json`, "
      "and rewrites this file. To refine a lesson's subject/teaches, edit the JSON and re-run.\n")

    with open("docs/CURRICULUM-MAP.md", "w", encoding="utf-8") as f:
        f.write("\n".join(o) + "\n")
    print(f"wrote docs/CURRICULUM-MAP.md — {len(order)} lessons, {len(exs)} exercises, "
          f"{backs} back-jumps, {len(no_ex)} gaps")


if __name__ == "__main__":
    main()
